### ISSUE TITLE
sweetiebot.sql does not create all necessary database stuff for bot to function

### ISSUE THREAD

**Issue by Jibodeah** [blackhole12/sweetiebot#13]
Specifically it doesn't create the `members` table or the `AddMember` procedure, the bot then complains about these during startup, and when added to a server. Possibly may be some others it needs to create, but it hasn't complained about any others.

Log:

    Preparing:  SELECT U.Username, M.FirstSeen FROM members M INNER JOIN users U ON M.ID = U.ID WHERE M.Guild = ? ORDER BY M.FirstSeen DESC LIMIT ? 
    SQL Error:  Error 1146: Table 'sweetiebot.members' doesn't exist
    Preparing:  SELECT CONCAT('Chatlog: ', (SELECT COUNT(*) FROM chatlog), ' rows', '
    Editlog: ', (SELECT COUNT(*) FROM editlog), ' rows',  '
    Aliases: ', (SELECT COUNT(*) FROM aliases), ' rows',  '
    Debuglog: ', (SELECT COUNT(*) FROM debuglog), ' rows',  '
    Pings: ', (SELECT COUNT(*) FROM pings), ' rows',  '
    Users: ', (SELECT COUNT(*) FROM users), ' rows 
    Members: ', (SELECT COUNT(*) FROM members), ' rows'); 
    SQL Error:  Error 1146: Table 'sweetiebot.members' doesn't exist
    Preparing:  SELECT COUNT(*) FROM members WHERE FirstSeen > DATE_SUB(NOW(), INTERVAL ? SECOND) AND Guild = ? 
    SQL Error:  Error 1146: Table 'sweetiebot.members' doesn't exist

Plus a bunch of the following when added to or joining a server:

    AddMember error: Error 1305: PROCEDURE sweetiebot.AddMember does not exist

This seems to the leave the bot unable to do anything, no response (in Discord nor in the console log) is obtained when sending commands.

**Comment by blackhole12** [comment]
Forgot to update the .sql file after some alterations, this has now been fixed.
