### ISSUE TITLE
Timezone Locations

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/sweetiebot#16]
Golang has a way to assign locations instead of just timezones, which allows for automatic daylight savings time compensation. Unfortunately, the database used is not included in the standard library and isn't even guaranteed to exist:

    The time zone database needed by LoadLocation may not be present on all systems, especially non-Unix systems. 

The only way to serialize the locations is to store the IANA location code, but because the database isn't guaranteed to exist or be up to date, the location stored in the database could cease to exist or not be present on certain systems. This is made even _worse_ because Go provides no way to query this database in the first place, so there is no way to obtain a list of the currently recognized timezone locations. This makes it impossible to do any sort of autocomplete or dropdown or _anything_ that doesn't require the user to know the magic code to their location, which is completely unworkable.

Until sweetiebot can get access to a reliable database of timezone locations **and have access to a list of all possible timezone location codes**, this feature cannot be implemented.

**Comment by TallonRain** [comment]
Here are a couple of sites with what appears to be updated data on current time zones and their respective information fields, for human reference.
http://www.timeanddate.com/time/zones/
http://www.timetemperature.com/abbreviations/world_time_zone_abbreviations.shtml

And, more usefully, here is a regularly updated database of time zone data. This appears to be an authoritative dataset. You may find this useful.

https://www.iana.org/time-zones

Along with what appears to be relevant information. Hopefully this will be helpful.

https://en.wikipedia.org/wiki/Tz_database
