### ISSUE TITLE
Zootopia server lastping takes from Manechat

### ISSUE THREAD

**Issue by TallonRain** [blackhole12/sweetiebot#19]
https://images-1.discordapp.net/.eJwNxVEOgyAMANC7cADKACl4G4IEzZQSWuPHsrtv7-d91D1PtapdZPAKsB1caG6ahWZuVTeidtY8DtaFLsgiuexX7cJgjY0LehNeMWFChwGsdRiNjx7D_7S4AHd_d3q6Hr2p7w8KMCL4.zUD4od8WMGSsZic6XsKnTQcbOS8.png

Reported by Chipmunk

**Comment by TallonRain** [comment]
"FYI Midnight Aegis I enabled database chat logging for the Zootopia server after ensuring there will be no leakage between the two." - Cloud Hop, 2016

**Comment by TallonRain** [comment]
UPDATE: it works both ways. Confirmed.

**Comment by TallonRain** [comment]
To elaborate, lastping will retrieve pings from both Zootopia and Manechat, regardless of what server a user is on when they use the lastping command.

**Comment by blackhole12** [comment]
Lastping is now completely isolated
