### ISSUE TITLE
how do i use antispam?

### ISSUE THREAD

**Issue by Smasher535** [blackhole12/sweetiebot#29]

**Comment by blackhole12** [comment]
First, set `maxraidtime` and `raidsize` to what you consider to be a raid. If a raid is "3 people join within 30 seconds of each other" then you would set `maxraidtime` to `30` and `raidsize` to `3`. Then, you'll want to set the spam type limits.

`maximagespam` should be set to the maximum number of images that can be attached to a single message. Should probably be at least 4.
`maxpingspam` is the maximum number of pings allowed in a single message. Should probably be set to around 10.
`maxmessagespam` is what determines how many messages per length of time is considered spam. So if you do `!setconfig maxmessagespam 1 4`, it tells sweetie bot to ban anyone who posts more than `4` messages in `1` second. Likewise, `!setconfig maxmessagespam 12 15` tells sweetiebot to ban anyone who posts more than `15` messages within `12` seconds of each other. A good default is `1 4`, `9 10`, `12 15`

If you configure a welcome channel via `!setconfig welcomechannel #welcomechannel`, you can use `!autosilence` to manage raids. See the help for `!autosilence` for more details.

**Comment by Smasher535** [comment]
Okay gonna try now thx

**Comment by Smasher535** [comment]
Theres no command called !set

**Comment by Smasher535** [comment]
Never mind it was !setconfig

**Comment by Smasher535** [comment]
But i dont want it to ban them, just mute them :(

**Comment by blackhole12** [comment]
Sweetie Bot never bans anyone, she only silences them.

**Comment by Smasher535** [comment]
But you said "sweetie will ban those who sends 4 msg per 1 s"

**Comment by Smasher535** [comment]
And if it silences, for how many secounds?

**Comment by blackhole12** [comment]
I meant silence, i updated the message, and sweetie bot silences them forever, until you unsilence them.

**Comment by Smasher535** [comment]
Ok thanks! Best bot ever
