### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by KohGeek** [blackhole12/sweetiebot#30]
When compiling, the below error shows up:

..\sweetiebot\sweetiebot.go:989: m.GuildBan undefined (type *discordgo.GuildBanAdd has no field or method GuildBan)
..\sweetiebot\sweetiebot.go:1000: m.GuildBan undefined (type *discordgo.GuildBanRemove has no field or method GuildBan)

**Comment by blackhole12** [comment]
An update in discordgo happened that changed the event structures, breaking the API. This should now be fixed.
