### ISSUE TITLE
Silencing feature request

### ISSUE THREAD

**Issue by seshormerow** [blackhole12/sweetiebot#36]
We have some issues with Sweetiebot with auto silencing our other bots on the server. I was wondering if it were possible if we could possibly get a feature to exempt specific roles on our server from being silenced. If it makes any difference I donated to the patreon for a couple of months under the name Colton Hooke.

**Comment by blackhole12** [comment]
You can now use `!setconfig spam.ignorerole @ignorerole` and anyone with that role will be excluded from anti-spam detection.
