### ISSUE TITLE
What The Fucking Fuck Is Up With This Fucking Token

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/sweetiebot#38]
According to @codeHusky, his installation of sweetiebot did not function properly until he appended "Bot " to the front of his token file. This should not be required because of this code:

    isuser, _ := ioutil.ReadFile("isuser")
    if isuser == nil {
        sb.dg, err = discordgo.New("Bot " + Token)
    } else {
        sb.dg, err = discordgo.New(Token)
        fmt.Println("Started SweetieBot on a user account.")
    }

@Moonwolf666 is now proposing for this to be removed from the installation instructions, but I want to know why the ever loving fuck it wasn't working for @codeHusky, preferably with a direct check on the resulting token actually sent through discordgo. Once I know what is actually going on instead of staring at tea leaves floating around a giant lake, the installation instructions can be properly amended.

**Comment by blackhole12** [comment]
Moral of the story: Do not create isuser unless you actually want the bot running in user mode, which you don't unless you are crazy. Clarifications have been made in the comments.

**Comment by codeHusky** [comment]
Removed isuser file and removed the Bot from my token file and it works fine. Derp.

**Comment by codeHusky** [comment]
In fact it works a bit better.
