### ISSUE TITLE
Zoneinfo Is Maintained By Fucking Idiots

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/sweetiebot#48]
Zoneinfo insists on listing every single timezone that ever existed or could ever theoretically exist (namely, `US/Pacific-NEW`), and does not provide a list that only includes timezones that are in active use right now, forcing me to instead synthesize this information from at least three different sources, because they're fucking assholes.

Sweetiebot's timezones should only include timezones that actually exist.

**Comment by blackhole12** [comment]
This file may or may not list the actual timezones we want: ftp://ftp.iana.org/tz/tzdb-2017b/zone1970.tab

**Comment by bb010g** [comment]
Here's the main bit from [Theory](ftp://ftp.iana.org/tz/tzdb-2017b/Theory) about `zone1970.tab`:
```

The file 'zone1970.tab' lists geographical locations used to name time
zone rules.  It is intended to be an exhaustive list of names for
geographic regions as described above; this is a subset of the names
in the data.  Although a 'zone1970.tab' location's longitude
corresponds to its LMT offset with one hour for every 15 degrees east
longitude, this relationship is not exact.
```
Everything else in there is pretty much just for historical accuracy or backwards-compatibility.

**Comment by blackhole12** [comment]
@bb010g This issue just got a whole lot more complicated, because not only have people assigned themselves to nonexistant timezones, 4 users have specifically assigned themselves to `US/Pacific-New`, which is precisely the timezone that specifically was supposed to be removed. At minimum, migration code would have to forcibly change those timezones to `US/Pacific` before it's even capable of updating the timezone table, but it's not clear what to do about people who assigned themselves to the `Etc/` area timezones.

**Comment by blackhole12** [comment]
This is not getting fixed. Pacific-New was removed, everything else is staying, timezones are fucking stupid, I'm not dealing with this bullshit anymore.
