### ISSUE TITLE
go build fails due to undefined references

### ISSUE THREAD

**Issue by spitefultowel** [blackhole12/sweetiebot#61]
Go build fails with the following errors.

> ../sweetiebot/sweetiebot.go:499: undefined: discordgo.ChannelType
> ../sweetiebot/sweetiebot.go:500: undefined: discordgo.ChannelTypeGuildText
> ../sweetiebot/sweetiebot.go:500: undefined: discordgo.ChannelTypeGuildCategory
> ../sweetiebot/sweetiebot.go:500: undefined: discordgo.ChannelTypeGuildVoice

**Comment by blackhole12** [comment]
From the readme:

> Note that sweetiebot requires the **develop branch** of discordgo. To switch, you will need to find where 
> Golang downloaded the discordgo library, open a terminal in that directory, and use the command git 
> checkout develop. Failure to do so will cause random compilation errors due to missing features. If 
> you're having any additional issues getting sweetiebot working, check INSTALLATION.md for more information.

**Comment by spitefultowel** [comment]
I didn't see that in the readme.md. I was following INSTALLATION.md which makes no mention of switching/downloading the development branch.

>**Install the required libraries with the commands go get github.com/go-sql-driver/mysql and go get github.com/blackhole12/discordgo.**

**Comment by blackhole12** [comment]
I deleted INSTALLATION.md, which was out of date.
