### ISSUE TITLE
Regex filter issue

### ISSUE THREAD

**Issue by AoElite** [blackhole12/sweetiebot#71]
So I made this regex to detect if someone posts a link that's not my website and every time I try to add it to a filter, it says it failed to add it because the regex compilation failed. I've checked the regex on multiple websites and on each one it works completely fine.

Regex: https?:\/\/(?!\w+\.?mywebsite)\w+

**Comment by blackhole12** [comment]
You are using negative backtracking via `(?!`, which is not supported by Go. Use this website to test your regex: https://regex-golang.appspot.com/assets/html/index.html

You will notice that your given regex fails to compile, because this website uses Go's regex engine.
